# WSU Server Base Vagrant Configuration
#
# Matches the WSU Server environment production setup as closely as possible.
# This will auto edit some of the local provisioning file but not the production.
# All production states/grains/pillars are to be managed by hand.
#
# We recommend Vagrant 1.3.5 and Virtualbox 4.3.
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

#######################
# Setup
######################
# There shouldn't be anything to edit below this point config wise
####################################################################


#require 'json'
# 	

################################################################ 
# Setup value defaults
################################################################ 

	#base dir
	################################################################ 
		#@vagrant_dir = File.expand_path(File.dirname(__FILE__))

	# the sub projects :: writes out the salt "config data" and 
	# sets up for vagrant.  The production is done by hand on purpose
	###############################################################
		@destroying=false
		ARGV.each do |arg|        
			if arg.include?'destroy'
				@destroying=true
			end
		end
		#load 'includes/vagrant_loadconfig.rb'


################################################################ 
# Start Vagrant
################################################################   
Vagrant.configure("2") do |config|
	load '.vagrant/includes/vagrant_env.rb'
 	config.ssh.pty = true 
		{% for name,server in servers -%}
			{% set vagrant = server.vagrant -%}
			{% set apps = server.apps -%}
			{% set hostname = vagrant.hostname | replace("-", "") | replace("_", "") -%}
			config.vm.define "{{ hostname }}" do |vmConfig|

			# Box choice
			################################################################
				vmConfig.vm.box_download_insecure = true
				{% if vagrant.box -%}
					vmConfig.vm.box     = "{{ vagrant.box }}"
					{% if vagrant.box_url -%}
						vmConfig.vm.box_url = "{{ vagrant.box_url }}"
					{% endif -%}
				{% else -%}
					vmConfig.vm.box     = "centos-64-x64-puppetlabs"
					vmConfig.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box"
				{% endif -%}


				if !@destroying 
					{% for appname,app in apps -%}
					{% if vagrant.hostname -%}
						{% set install_dir = app.install_dir -%}
					{% else -%}
						{% set install_dir = appname -%}
					{% endif -%}
					if !File.exist?("server/app/{{ install_dir }}")
						puts "cloning repo that was missing"
						puts "git clone {{ app.repo }} server/app/{{ install_dir }}"
						puts `git clone --depth=1 {{ app.repo }} server/app/{{ install_dir }}`
					end
					{% endfor -%}
				end

				#load 'includes/automated_salt_setup.rb'

				# Virtualbox specific settings for the virtual machine.
				################################################################ 
					vmConfig.vm.provider :virtualbox do |v|
						v.gui = {{ vagrant.gui }}
						{% if hostname -%}
							v.name = "{{ hostname }}"
						{% endif -%}
							v.memory = {{ vagrant.memory }}
						{% if vagrant.vram>8 -%}
							v.customize ["modifyvm", :id, "--vram", {{ vagrant.vram }}]
						{% endif -%}
						{% if vagrant.cores>1 -%}
							v.customize ["modifyvm", :id, "--cpus", {{ vagrant.cores }} ]
						{% endif -%}
						{% if vagrant.host_64bit -%}
							#v.customize ["modifyvm", :id, "--ioapic", "on"]
						{% endif -%}
					end

				# Set networking options
				################################################################   
					{% if hostname -%}
						vmConfig.vm.hostname = '{{ hostname }}'
					{% endif -%}
					vmConfig.vm.network :private_network, ip: "{{ vagrant.ip }}"

				{% if apps -%}
				# register hosts for all hosts for apps and the server
				################################################################
				# Local Machine Hosts
				# Capture the paths to all `hosts` from apps.
					
					hosts = [{% for appname,app in apps -%}
							{% for host in app.vagrant.hosts -%}"{{ host }}"{% if  not loop.last -%},{% endif -%}
							{% endfor -%}
					{% endfor -%} ]


					if defined? VagrantPlugins::HostsUpdater
						vmConfig.hostsupdater.aliases = hosts
					end

					vmConfig.vm.provision :hosts do |provisioner|
						provisioner.add_host '127.0.0.1', hosts
					end
				{% endif -%}

				# Provisioning: Salt based
				################################################################
					# we are marking the server that it's a vagrant control server for dev usage
					vmConfig.vm.provision :shell, :inline => "echo 'export SERVER_TYPE=\"VAGRANT\"' >> /etc/environment"
						# Set file mounts
						################################################################           
						# Mount the local project's server/app/ directory as /var/app inside the virtual machine. This will
						# be mounted as the 'vagrant' user at first, then unmounted and mounted again as 'www-data'
						# during provisioning.
						{% for fname,fobj in vagrant.shared_folders -%}
							vmConfig.vm.synced_folder "{{ fobj.from }}", "{{ fobj.dest }}", :mount_options => [ "{{ fobj.user }}", "{{ fobj.dmode }}", "{{ fobj.fmode }}" ]
						{% endfor -%}

						vmConfig.vm.provision "shell", inline: "sh /vagrant/server-bootstrap.sh"
							
					#if !@destroying
					#	$running="echo \"about to run running: #{$provision_script} \" \n"
					#	vmConfig.vm.provision "shell", inline: "#{$running}#{$provision_script}"
					#else
					#	puts "About to destroy the local server"
					#end
			end
		{% endfor %}

end
